name: game-boulette
region: sfo
services:
- dockerfile_path: /GameBoulette/GameBoulette.Server/Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: MaxThom/game-boulette-v2
  http_port: 8080
  instance_count: 1
  instance_size_slug: professional-xs
  name: game-boulette
  routes:
  - path: /
  health_check:
    http_path: /api/health
  source_dir: /GameBoulette/